# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Cedai_Engine_config = debug
  Cedai_Model_Converter_config = debug

else ifeq ($(config),release)
  Cedai_Engine_config = release
  Cedai_Model_Converter_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Cedai_Engine Cedai_Model_Converter

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Cedai_Engine:
ifneq (,$(Cedai_Engine_config))
	@echo "==== Building Cedai_Engine ($(Cedai_Engine_config)) ===="
	@${MAKE} --no-print-directory -C Cedai_Engine -f Makefile config=$(Cedai_Engine_config)
endif

Cedai_Model_Converter:
ifneq (,$(Cedai_Model_Converter_config))
	@echo "==== Building Cedai_Model_Converter ($(Cedai_Model_Converter_config)) ===="
	@${MAKE} --no-print-directory -C Cedai_Model_Converter -f Makefile config=$(Cedai_Model_Converter_config)
endif

clean:
	@${MAKE} --no-print-directory -C Cedai_Engine -f Makefile clean
	@${MAKE} --no-print-directory -C Cedai_Model_Converter -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Cedai_Engine"
	@echo "   Cedai_Model_Converter"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"